# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cursos.ui'
#
# Created: Sun Jun 16 14:13:16 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(465, 361)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.dockWidget = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget.setGeometry(QtCore.QRect(20, 10, 431, 311))
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.busquedaLbl = QtGui.QLabel(self.dockWidgetContents)
        self.busquedaLbl.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.busquedaLbl.setObjectName(_fromUtf8("busquedaLbl"))
        self.FiltroComboBox = QtGui.QComboBox(self.dockWidgetContents)
        self.FiltroComboBox.setGeometry(QtCore.QRect(70, 40, 111, 22))
        self.FiltroComboBox.setObjectName(_fromUtf8("FiltroComboBox"))
        self.busquedaTxt = QtGui.QLineEdit(self.dockWidgetContents)
        self.busquedaTxt.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.busquedaTxt.setObjectName(_fromUtf8("busquedaTxt"))
        self.filtroLbl = QtGui.QLabel(self.dockWidgetContents)
        self.filtroLbl.setGeometry(QtCore.QRect(10, 40, 46, 13))
        self.filtroLbl.setObjectName(_fromUtf8("filtroLbl"))
        self.infoTableWidget = QtGui.QTableWidget(self.dockWidgetContents)
        self.infoTableWidget.setGeometry(QtCore.QRect(10, 70, 401, 192))
        self.infoTableWidget.setObjectName(_fromUtf8("infoTableWidget"))
        self.infoTableWidget.setColumnCount(0)
        self.infoTableWidget.setRowCount(0)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCursos = QtGui.QMenu(self.menubar)
        self.menuCursos.setObjectName(_fromUtf8("menuCursos"))
        self.menuVer = QtGui.QMenu(self.menuCursos)
        self.menuVer.setObjectName(_fromUtf8("menuVer"))
        self.menuAgregar = QtGui.QMenu(self.menuCursos)
        self.menuAgregar.setObjectName(_fromUtf8("menuAgregar"))
        self.menuAlumnos = QtGui.QMenu(self.menubar)
        self.menuAlumnos.setObjectName(_fromUtf8("menuAlumnos"))
        self.menuAgregarAlumno = QtGui.QMenu(self.menuAlumnos)
        self.menuAgregarAlumno.setObjectName(_fromUtf8("menuAgregarAlumno"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionVerLista_cursos = QtGui.QAction(MainWindow)
        self.actionVerLista_cursos.setObjectName(_fromUtf8("actionVerLista_cursos"))
        self.actionVerAlumnos = QtGui.QAction(MainWindow)
        self.actionVerAlumnos.setObjectName(_fromUtf8("actionVerAlumnos"))
        self.actionAlumno = QtGui.QAction(MainWindow)
        self.actionAlumno.setObjectName(_fromUtf8("actionAlumno"))
        self.actionCurso = QtGui.QAction(MainWindow)
        self.actionCurso.setObjectName(_fromUtf8("actionCurso"))
        self.actionTemporada = QtGui.QAction(MainWindow)
        self.actionTemporada.setObjectName(_fromUtf8("actionTemporada"))
        self.actionAgregaCurso = QtGui.QAction(MainWindow)
        self.actionAgregaCurso.setObjectName(_fromUtf8("actionAgregaCurso"))
        self.actionAgregarMaestro = QtGui.QAction(MainWindow)
        self.actionAgregarMaestro.setObjectName(_fromUtf8("actionAgregarMaestro"))
        self.actionAgregarEstudiante = QtGui.QAction(MainWindow)
        self.actionAgregarEstudiante.setObjectName(_fromUtf8("actionAgregarEstudiante"))
        self.actionVerMaestros = QtGui.QAction(MainWindow)
        self.actionVerMaestros.setObjectName(_fromUtf8("actionVerMaestros"))
        self.actionVerEstudiantes = QtGui.QAction(MainWindow)
        self.actionVerEstudiantes.setObjectName(_fromUtf8("actionVerEstudiantes"))
        self.actionVerAlumno = QtGui.QAction(MainWindow)
        self.actionVerAlumno.setObjectName(_fromUtf8("actionVerAlumno"))
        self.actionAyudante_2 = QtGui.QAction(MainWindow)
        self.actionAyudante_2.setObjectName(_fromUtf8("actionAyudante_2"))
        self.actionVerLista_asistencia = QtGui.QAction(MainWindow)
        self.actionVerLista_asistencia.setObjectName(_fromUtf8("actionVerLista_asistencia"))
        self.actionCausa_falta = QtGui.QAction(MainWindow)
        self.actionCausa_falta.setObjectName(_fromUtf8("actionCausa_falta"))
        self.actionNuevo = QtGui.QAction(MainWindow)
        self.actionNuevo.setObjectName(_fromUtf8("actionNuevo"))
        self.actionNuevoAlumno = QtGui.QAction(MainWindow)
        self.actionNuevoAlumno.setObjectName(_fromUtf8("actionNuevoAlumno"))
        self.actionExistente = QtGui.QAction(MainWindow)
        self.actionExistente.setObjectName(_fromUtf8("actionExistente"))
        self.menuVer.addAction(self.actionVerLista_cursos)
        self.menuVer.addAction(self.actionVerMaestros)
        self.menuVer.addAction(self.actionVerEstudiantes)
        self.menuVer.addAction(self.actionVerLista_asistencia)
        self.menuAgregar.addAction(self.actionAgregaCurso)
        self.menuAgregar.addAction(self.actionAgregarMaestro)
        self.menuAgregar.addAction(self.actionAgregarEstudiante)
        self.menuAgregar.addAction(self.actionCausa_falta)
        self.menuCursos.addAction(self.menuAgregar.menuAction())
        self.menuCursos.addAction(self.menuVer.menuAction())
        self.menuAgregarAlumno.addAction(self.actionNuevoAlumno)
        self.menuAgregarAlumno.addAction(self.actionExistente)
        self.menuAlumnos.addAction(self.menuAgregarAlumno.menuAction())
        self.menuAlumnos.addAction(self.actionVerAlumno)
        self.menubar.addAction(self.menuCursos.menuAction())
        self.menubar.addAction(self.menuAlumnos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionAgregaCurso, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.agregarCurso)
        QtCore.QObject.connect(self.actionAgregarEstudiante, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.agregarEstudianteCurso)
        QtCore.QObject.connect(self.actionAgregarMaestro, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.agregarMaestroCurso)
        QtCore.QObject.connect(self.actionCausa_falta, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.agregarCausaFaltaCurso)
        QtCore.QObject.connect(self.actionVerLista_cursos, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.verCatalogoCursos)
        QtCore.QObject.connect(self.actionVerMaestros, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.verMaestros)
        QtCore.QObject.connect(self.actionVerEstudiantes, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.verEstudiantes)
        QtCore.QObject.connect(self.actionVerLista_asistencia, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.verListaAsistencia)
        QtCore.QObject.connect(self.actionNuevoAlumno, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.agregarAlumnoCurso)
        QtCore.QObject.connect(self.actionExistente, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.agregarAlumnoCurso)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.busquedaLbl.setText(_translate("MainWindow", "Busqueda:", None))
        self.filtroLbl.setText(_translate("MainWindow", "Filtro:", None))
        self.menuCursos.setTitle(_translate("MainWindow", "Cursos", None))
        self.menuVer.setTitle(_translate("MainWindow", "Ver ", None))
        self.menuAgregar.setTitle(_translate("MainWindow", "Agregar", None))
        self.menuAlumnos.setTitle(_translate("MainWindow", "Alumnos", None))
        self.menuAgregarAlumno.setTitle(_translate("MainWindow", "Agregar", None))
        self.actionVerLista_cursos.setText(_translate("MainWindow", "Catalogo de cursos", None))
        self.actionVerAlumnos.setText(_translate("MainWindow", "Alumnos", None))
        self.actionAlumno.setText(_translate("MainWindow", "Alumno", None))
        self.actionCurso.setText(_translate("MainWindow", "Edad", None))
        self.actionTemporada.setText(_translate("MainWindow", "Maestro", None))
        self.actionAgregaCurso.setText(_translate("MainWindow", "Curso", None))
        self.actionAgregarMaestro.setText(_translate("MainWindow", "Maestro", None))
        self.actionAgregarEstudiante.setText(_translate("MainWindow", "Estudiante", None))
        self.actionVerMaestros.setText(_translate("MainWindow", "Maestros", None))
        self.actionVerEstudiantes.setText(_translate("MainWindow", "Estudiante", None))
        self.actionVerAlumno.setText(_translate("MainWindow", "Ver", None))
        self.actionAyudante_2.setText(_translate("MainWindow", "Estudiante", None))
        self.actionVerLista_asistencia.setText(_translate("MainWindow", "Lista asistencia", None))
        self.actionCausa_falta.setText(_translate("MainWindow", "Causa falta", None))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo", None))
        self.actionNuevoAlumno.setText(_translate("MainWindow", "Nuevo", None))
        self.actionExistente.setText(_translate("MainWindow", "Existente", None))

