# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgregarPersona.ui'
#
# Created: Sun Jun 16 14:12:18 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(534, 450)
        Form.setAutoFillBackground(False)
        self.aceptarBtn = QtGui.QPushButton(Form)
        self.aceptarBtn.setGeometry(QtCore.QRect(330, 410, 75, 23))
        self.aceptarBtn.setObjectName(_fromUtf8("aceptarBtn"))
        self.cancelarBtn = QtGui.QPushButton(Form)
        self.cancelarBtn.setGeometry(QtCore.QRect(430, 410, 75, 23))
        self.cancelarBtn.setObjectName(_fromUtf8("cancelarBtn"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 501, 371))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.amLbl = QtGui.QLabel(self.groupBox)
        self.amLbl.setGeometry(QtCore.QRect(30, 100, 81, 16))
        self.amLbl.setObjectName(_fromUtf8("amLbl"))
        self.telefonoTxt = QtGui.QLineEdit(self.groupBox)
        self.telefonoTxt.setGeometry(QtCore.QRect(370, 40, 113, 21))
        self.telefonoTxt.setObjectName(_fromUtf8("telefonoTxt"))
        self.gradoEscolarLbl = QtGui.QLabel(self.groupBox)
        self.gradoEscolarLbl.setGeometry(QtCore.QRect(30, 280, 81, 16))
        self.gradoEscolarLbl.setObjectName(_fromUtf8("gradoEscolarLbl"))
        self.nombreLbl = QtGui.QLabel(self.groupBox)
        self.nombreLbl.setGeometry(QtCore.QRect(30, 40, 46, 13))
        self.nombreLbl.setObjectName(_fromUtf8("nombreLbl"))
        self.gradoEscolarComboBox = QtGui.QComboBox(self.groupBox)
        self.gradoEscolarComboBox.setGeometry(QtCore.QRect(120, 280, 111, 21))
        self.gradoEscolarComboBox.setObjectName(_fromUtf8("gradoEscolarComboBox"))
        self.celularTxt = QtGui.QLineEdit(self.groupBox)
        self.celularTxt.setGeometry(QtCore.QRect(370, 70, 113, 21))
        self.celularTxt.setObjectName(_fromUtf8("celularTxt"))
        self.generoLbl = QtGui.QLabel(self.groupBox)
        self.generoLbl.setGeometry(QtCore.QRect(30, 130, 46, 13))
        self.generoLbl.setObjectName(_fromUtf8("generoLbl"))
        self.celularLbl = QtGui.QLabel(self.groupBox)
        self.celularLbl.setGeometry(QtCore.QRect(270, 70, 46, 13))
        self.celularLbl.setObjectName(_fromUtf8("celularLbl"))
        self.emailLbl = QtGui.QLabel(self.groupBox)
        self.emailLbl.setGeometry(QtCore.QRect(270, 100, 101, 16))
        self.emailLbl.setObjectName(_fromUtf8("emailLbl"))
        self.fechaNac = QtGui.QDateEdit(self.groupBox)
        self.fechaNac.setGeometry(QtCore.QRect(120, 160, 110, 21))
        self.fechaNac.setObjectName(_fromUtf8("fechaNac"))
        self.telefonoLbl = QtGui.QLabel(self.groupBox)
        self.telefonoLbl.setGeometry(QtCore.QRect(270, 40, 46, 13))
        self.telefonoLbl.setObjectName(_fromUtf8("telefonoLbl"))
        self.domicilioLbl = QtGui.QLabel(self.groupBox)
        self.domicilioLbl.setGeometry(QtCore.QRect(30, 190, 46, 13))
        self.domicilioLbl.setObjectName(_fromUtf8("domicilioLbl"))
        self.domicilioTxt = QtGui.QLineEdit(self.groupBox)
        self.domicilioTxt.setGeometry(QtCore.QRect(120, 190, 113, 21))
        self.domicilioTxt.setObjectName(_fromUtf8("domicilioTxt"))
        self.coloniaComboBox = QtGui.QComboBox(self.groupBox)
        self.coloniaComboBox.setGeometry(QtCore.QRect(120, 220, 111, 21))
        self.coloniaComboBox.setObjectName(_fromUtf8("coloniaComboBox"))
        self.coloniaLbl = QtGui.QLabel(self.groupBox)
        self.coloniaLbl.setGeometry(QtCore.QRect(30, 220, 46, 13))
        self.coloniaLbl.setObjectName(_fromUtf8("coloniaLbl"))
        self.emailTxt = QtGui.QLineEdit(self.groupBox)
        self.emailTxt.setGeometry(QtCore.QRect(370, 100, 113, 21))
        self.emailTxt.setObjectName(_fromUtf8("emailTxt"))
        self.codigoPostalLbl = QtGui.QLabel(self.groupBox)
        self.codigoPostalLbl.setGeometry(QtCore.QRect(30, 250, 71, 16))
        self.codigoPostalLbl.setObjectName(_fromUtf8("codigoPostalLbl"))
        self.apTxt_2 = QtGui.QLineEdit(self.groupBox)
        self.apTxt_2.setGeometry(QtCore.QRect(120, 100, 113, 21))
        self.apTxt_2.setObjectName(_fromUtf8("apTxt_2"))
        self.monitoreoLbl = QtGui.QLabel(self.groupBox)
        self.monitoreoLbl.setGeometry(QtCore.QRect(270, 130, 61, 16))
        self.monitoreoLbl.setObjectName(_fromUtf8("monitoreoLbl"))
        self.generoComboBox = QtGui.QComboBox(self.groupBox)
        self.generoComboBox.setGeometry(QtCore.QRect(120, 130, 111, 21))
        self.generoComboBox.setObjectName(_fromUtf8("generoComboBox"))
        self.codigoPostalTxt = QtGui.QLineEdit(self.groupBox)
        self.codigoPostalTxt.setGeometry(QtCore.QRect(120, 250, 113, 21))
        self.codigoPostalTxt.setObjectName(_fromUtf8("codigoPostalTxt"))
        self.fechaNacLbl = QtGui.QLabel(self.groupBox)
        self.fechaNacLbl.setGeometry(QtCore.QRect(30, 160, 91, 16))
        self.fechaNacLbl.setObjectName(_fromUtf8("fechaNacLbl"))
        self.apTxt = QtGui.QLineEdit(self.groupBox)
        self.apTxt.setGeometry(QtCore.QRect(120, 70, 113, 21))
        self.apTxt.setObjectName(_fromUtf8("apTxt"))
        self.monitoreoComboBox = QtGui.QComboBox(self.groupBox)
        self.monitoreoComboBox.setGeometry(QtCore.QRect(370, 130, 111, 21))
        self.monitoreoComboBox.setObjectName(_fromUtf8("monitoreoComboBox"))
        self.nombreTxt = QtGui.QLineEdit(self.groupBox)
        self.nombreTxt.setGeometry(QtCore.QRect(120, 40, 113, 21))
        self.nombreTxt.setObjectName(_fromUtf8("nombreTxt"))
        self.apLbl = QtGui.QLabel(self.groupBox)
        self.apLbl.setGeometry(QtCore.QRect(30, 70, 91, 16))
        self.apLbl.setObjectName(_fromUtf8("apLbl"))
        self.areaLbl = QtGui.QLabel(self.groupBox)
        self.areaLbl.setGeometry(QtCore.QRect(270, 160, 46, 13))
        self.areaLbl.setObjectName(_fromUtf8("areaLbl"))
        self.puestoEscuelaLbl = QtGui.QLabel(self.groupBox)
        self.puestoEscuelaLbl.setGeometry(QtCore.QRect(270, 190, 46, 13))
        self.puestoEscuelaLbl.setObjectName(_fromUtf8("puestoEscuelaLbl"))
        self.usuarioTelEmeLbl = QtGui.QLabel(self.groupBox)
        self.usuarioTelEmeLbl.setGeometry(QtCore.QRect(270, 220, 46, 13))
        self.usuarioTelEmeLbl.setObjectName(_fromUtf8("usuarioTelEmeLbl"))
        self.contrasenaNombreResLbl = QtGui.QLabel(self.groupBox)
        self.contrasenaNombreResLbl.setGeometry(QtCore.QRect(270, 250, 46, 13))
        self.contrasenaNombreResLbl.setObjectName(_fromUtf8("contrasenaNombreResLbl"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(270, 280, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.fechaInicioLbl = QtGui.QLabel(self.groupBox)
        self.fechaInicioLbl.setGeometry(QtCore.QRect(30, 310, 71, 16))
        self.fechaInicioLbl.setObjectName(_fromUtf8("fechaInicioLbl"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(270, 310, 101, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fechaFinLbl = QtGui.QLabel(self.groupBox)
        self.fechaFinLbl.setGeometry(QtCore.QRect(30, 340, 61, 16))
        self.fechaFinLbl.setObjectName(_fromUtf8("fechaFinLbl"))
        self.areaComboBox = QtGui.QComboBox(self.groupBox)
        self.areaComboBox.setGeometry(QtCore.QRect(370, 160, 111, 22))
        self.areaComboBox.setObjectName(_fromUtf8("areaComboBox"))
        self.contrasenaNombreResTxt = QtGui.QLineEdit(self.groupBox)
        self.contrasenaNombreResTxt.setGeometry(QtCore.QRect(370, 250, 113, 20))
        self.contrasenaNombreResTxt.setObjectName(_fromUtf8("contrasenaNombreResTxt"))
        self.usuarioTelEmeTxt = QtGui.QLineEdit(self.groupBox)
        self.usuarioTelEmeTxt.setGeometry(QtCore.QRect(370, 220, 113, 20))
        self.usuarioTelEmeTxt.setObjectName(_fromUtf8("usuarioTelEmeTxt"))
        self.puestoEscuelaComboBox = QtGui.QComboBox(self.groupBox)
        self.puestoEscuelaComboBox.setGeometry(QtCore.QRect(370, 190, 111, 22))
        self.puestoEscuelaComboBox.setObjectName(_fromUtf8("puestoEscuelaComboBox"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 280, 113, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 310, 113, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.dateEdit = QtGui.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(120, 310, 110, 21))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.dateEdit_2 = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(120, 340, 110, 21))
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.aceptarBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.agregarPersona)
        QtCore.QObject.connect(self.cancelarBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.cancelar)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.aceptarBtn.setText(_translate("Form", "Aceptar", None))
        self.cancelarBtn.setText(_translate("Form", "Cancelar", None))
        self.groupBox.setTitle(_translate("Form", "Datos Persona", None))
        self.amLbl.setText(_translate("Form", "Apellid Paterno:", None))
        self.gradoEscolarLbl.setText(_translate("Form", "Grado Escolar:", None))
        self.nombreLbl.setText(_translate("Form", "Nombre:", None))
        self.generoLbl.setText(_translate("Form", "Genero:", None))
        self.celularLbl.setText(_translate("Form", "Celular:", None))
        self.emailLbl.setText(_translate("Form", "E-Mail:", None))
        self.telefonoLbl.setText(_translate("Form", "Telefono:", None))
        self.domicilioLbl.setText(_translate("Form", "Domicilio:", None))
        self.coloniaLbl.setText(_translate("Form", "Colonia:", None))
        self.codigoPostalLbl.setText(_translate("Form", "Codigo Postal:", None))
        self.monitoreoLbl.setText(_translate("Form", "Monitoreo:", None))
        self.fechaNacLbl.setText(_translate("Form", "Fecha Nacimiento:", None))
        self.apLbl.setText(_translate("Form", "Apellido Materno:", None))
        self.areaLbl.setText(_translate("Form", "Área:", None))
        self.puestoEscuelaLbl.setText(_translate("Form", "temp", None))
        self.usuarioTelEmeLbl.setText(_translate("Form", "temp", None))
        self.contrasenaNombreResLbl.setText(_translate("Form", "temp", None))
        self.label_5.setText(_translate("Form", "Tel. Responsable:", None))
        self.fechaInicioLbl.setText(_translate("Form", "Fecha inicio:", None))
        self.label_7.setText(_translate("Form", "E-Mail Responsable:", None))
        self.fechaFinLbl.setText(_translate("Form", "Fecha fin:", None))

