# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgregarPersona.ui'
#
# Created: Fri Feb 07 00:00:20 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import QComboBoxWrapper

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(610, 450)
        Form.setAutoFillBackground(False)
        self.aceptarBtn = QtGui.QPushButton(Form)
        self.aceptarBtn.setGeometry(QtCore.QRect(410, 410, 75, 23))
        self.aceptarBtn.setObjectName(_fromUtf8("aceptarBtn"))
        self.cancelarBtn = QtGui.QPushButton(Form)
        self.cancelarBtn.setGeometry(QtCore.QRect(510, 410, 75, 23))
        self.cancelarBtn.setObjectName(_fromUtf8("cancelarBtn"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 571, 371))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.amLbl = QtGui.QLabel(self.groupBox)
        self.amLbl.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.amLbl.setObjectName(_fromUtf8("amLbl"))
        self.telefonoTxt = QtGui.QLineEdit(self.groupBox)
        self.telefonoTxt.setGeometry(QtCore.QRect(400, 40, 141, 21))
        self.telefonoTxt.setObjectName(_fromUtf8("telefonoTxt"))
        self.gradoEscolarLbl = QtGui.QLabel(self.groupBox)
        self.gradoEscolarLbl.setGeometry(QtCore.QRect(30, 280, 81, 16))
        self.gradoEscolarLbl.setObjectName(_fromUtf8("gradoEscolarLbl"))
        self.nombreLbl = QtGui.QLabel(self.groupBox)
        self.nombreLbl.setGeometry(QtCore.QRect(30, 40, 46, 13))
        self.nombreLbl.setObjectName(_fromUtf8("nombreLbl"))
        self.gradoEscolarComboBox = QComboBoxWrapper.QComboBoxWrapper(self.groupBox)
        self.gradoEscolarComboBox.setGeometry(QtCore.QRect(120, 280, 141, 21))
        self.gradoEscolarComboBox.setObjectName(_fromUtf8("gradoEscolarComboBox"))
        self.celularTxt = QtGui.QLineEdit(self.groupBox)
        self.celularTxt.setGeometry(QtCore.QRect(400, 70, 141, 21))
        self.celularTxt.setObjectName(_fromUtf8("celularTxt"))
        self.generoLbl = QtGui.QLabel(self.groupBox)
        self.generoLbl.setGeometry(QtCore.QRect(30, 130, 46, 13))
        self.generoLbl.setObjectName(_fromUtf8("generoLbl"))
        self.celularLbl = QtGui.QLabel(self.groupBox)
        self.celularLbl.setGeometry(QtCore.QRect(290, 70, 46, 13))
        self.celularLbl.setObjectName(_fromUtf8("celularLbl"))
        self.emailLbl = QtGui.QLabel(self.groupBox)
        self.emailLbl.setGeometry(QtCore.QRect(290, 100, 101, 16))
        self.emailLbl.setObjectName(_fromUtf8("emailLbl"))
        self.fechaNacDate = QtGui.QDateEdit(self.groupBox)
        self.fechaNacDate.setGeometry(QtCore.QRect(120, 160, 141, 21))
        self.fechaNacDate.setObjectName(_fromUtf8("fechaNacDate"))
        self.telefonoLbl = QtGui.QLabel(self.groupBox)
        self.telefonoLbl.setGeometry(QtCore.QRect(290, 40, 46, 13))
        self.telefonoLbl.setObjectName(_fromUtf8("telefonoLbl"))
        self.domicilioLbl = QtGui.QLabel(self.groupBox)
        self.domicilioLbl.setGeometry(QtCore.QRect(30, 190, 46, 13))
        self.domicilioLbl.setObjectName(_fromUtf8("domicilioLbl"))
        self.domicilioTxt = QtGui.QLineEdit(self.groupBox)
        self.domicilioTxt.setGeometry(QtCore.QRect(120, 190, 141, 21))
        self.domicilioTxt.setObjectName(_fromUtf8("domicilioTxt"))
        self.coloniaComboBox = QComboBoxWrapper.QComboBoxWrapper(self.groupBox)
        self.coloniaComboBox.setGeometry(QtCore.QRect(120, 220, 141, 21))
        self.coloniaComboBox.setObjectName(_fromUtf8("coloniaComboBox"))
        self.coloniaLbl = QtGui.QLabel(self.groupBox)
        self.coloniaLbl.setGeometry(QtCore.QRect(30, 220, 46, 13))
        self.coloniaLbl.setObjectName(_fromUtf8("coloniaLbl"))
        self.emailTxt = QtGui.QLineEdit(self.groupBox)
        self.emailTxt.setGeometry(QtCore.QRect(400, 100, 141, 21))
        self.emailTxt.setObjectName(_fromUtf8("emailTxt"))
        self.codigoPostalLbl = QtGui.QLabel(self.groupBox)
        self.codigoPostalLbl.setGeometry(QtCore.QRect(30, 250, 71, 16))
        self.codigoPostalLbl.setObjectName(_fromUtf8("codigoPostalLbl"))
        self.apTxt = QtGui.QLineEdit(self.groupBox)
        self.apTxt.setGeometry(QtCore.QRect(120, 70, 141, 21))
        self.apTxt.setObjectName(_fromUtf8("apTxt"))
        self.monitoreoAreaLbl = QtGui.QLabel(self.groupBox)
        self.monitoreoAreaLbl.setGeometry(QtCore.QRect(290, 130, 61, 16))
        self.monitoreoAreaLbl.setObjectName(_fromUtf8("monitoreoAreaLbl"))
        self.generoComboBox = QComboBoxWrapper.QComboBoxWrapper(self.groupBox)
        self.generoComboBox.setGeometry(QtCore.QRect(120, 130, 141, 21))
        self.generoComboBox.setEditable(False)
        self.generoComboBox.setObjectName(_fromUtf8("generoComboBox"))
        self.codigoPostalTxt = QtGui.QLineEdit(self.groupBox)
        self.codigoPostalTxt.setGeometry(QtCore.QRect(120, 250, 141, 21))
        self.codigoPostalTxt.setObjectName(_fromUtf8("codigoPostalTxt"))
        self.fechaNacLbl = QtGui.QLabel(self.groupBox)
        self.fechaNacLbl.setGeometry(QtCore.QRect(30, 160, 91, 16))
        self.fechaNacLbl.setObjectName(_fromUtf8("fechaNacLbl"))
        self.amTxt = QtGui.QLineEdit(self.groupBox)
        self.amTxt.setGeometry(QtCore.QRect(120, 100, 141, 21))
        self.amTxt.setObjectName(_fromUtf8("amTxt"))
        self.monitoreoAreaComboBox = QComboBoxWrapper.QComboBoxWrapper(self.groupBox)
        self.monitoreoAreaComboBox.setGeometry(QtCore.QRect(400, 130, 141, 21))
        self.monitoreoAreaComboBox.setObjectName(_fromUtf8("monitoreoAreaComboBox"))
        self.nombreTxt = QtGui.QLineEdit(self.groupBox)
        self.nombreTxt.setGeometry(QtCore.QRect(120, 40, 141, 21))
        self.nombreTxt.setObjectName(_fromUtf8("nombreTxt"))
        self.apLbl = QtGui.QLabel(self.groupBox)
        self.apLbl.setGeometry(QtCore.QRect(30, 100, 91, 16))
        self.apLbl.setObjectName(_fromUtf8("apLbl"))
        self.escuelaPuestoLbl = QtGui.QLabel(self.groupBox)
        self.escuelaPuestoLbl.setGeometry(QtCore.QRect(290, 190, 91, 16))
        self.escuelaPuestoLbl.setObjectName(_fromUtf8("escuelaPuestoLbl"))
        self.permisosLbl = QtGui.QLabel(self.groupBox)
        self.permisosLbl.setGeometry(QtCore.QRect(290, 160, 91, 16))
        self.permisosLbl.setObjectName(_fromUtf8("permisosLbl"))
        self.usuarioTelEmeLbl = QtGui.QLabel(self.groupBox)
        self.usuarioTelEmeLbl.setGeometry(QtCore.QRect(290, 220, 91, 16))
        self.usuarioTelEmeLbl.setObjectName(_fromUtf8("usuarioTelEmeLbl"))
        self.contrasenaNombreResLbl = QtGui.QLabel(self.groupBox)
        self.contrasenaNombreResLbl.setGeometry(QtCore.QRect(290, 250, 91, 16))
        self.contrasenaNombreResLbl.setObjectName(_fromUtf8("contrasenaNombreResLbl"))
        self.verifiContrasenaTelRespLbl = QtGui.QLabel(self.groupBox)
        self.verifiContrasenaTelRespLbl.setGeometry(QtCore.QRect(290, 280, 91, 16))
        self.verifiContrasenaTelRespLbl.setObjectName(_fromUtf8("verifiContrasenaTelRespLbl"))
        self.fechaInicioLbl = QtGui.QLabel(self.groupBox)
        self.fechaInicioLbl.setGeometry(QtCore.QRect(30, 310, 71, 16))
        self.fechaInicioLbl.setObjectName(_fromUtf8("fechaInicioLbl"))
        self.emailRespLbl = QtGui.QLabel(self.groupBox)
        self.emailRespLbl.setGeometry(QtCore.QRect(290, 310, 111, 16))
        self.emailRespLbl.setObjectName(_fromUtf8("emailRespLbl"))
        self.fechaFinLbl = QtGui.QLabel(self.groupBox)
        self.fechaFinLbl.setGeometry(QtCore.QRect(30, 340, 61, 16))
        self.fechaFinLbl.setObjectName(_fromUtf8("fechaFinLbl"))
        self.escuelaPuestoComboBox = QComboBoxWrapper.QComboBoxWrapper(self.groupBox)
        self.escuelaPuestoComboBox.setGeometry(QtCore.QRect(400, 190, 141, 22))
        self.escuelaPuestoComboBox.setObjectName(_fromUtf8("escuelaPuestoComboBox"))
        self.contrasenaNombreResTxt = QtGui.QLineEdit(self.groupBox)
        self.contrasenaNombreResTxt.setGeometry(QtCore.QRect(400, 250, 141, 20))
        self.contrasenaNombreResTxt.setObjectName(_fromUtf8("contrasenaNombreResTxt"))
        self.usuarioTelEmeTxt = QtGui.QLineEdit(self.groupBox)
        self.usuarioTelEmeTxt.setGeometry(QtCore.QRect(400, 220, 141, 20))
        self.usuarioTelEmeTxt.setObjectName(_fromUtf8("usuarioTelEmeTxt"))
        self.permisosComboBox = QComboBoxWrapper.QComboBoxWrapper(self.groupBox)
        self.permisosComboBox.setGeometry(QtCore.QRect(400, 160, 141, 22))
        self.permisosComboBox.setObjectName(_fromUtf8("permisosComboBox"))
        self.verifiContrasenaTelRespTxt = QtGui.QLineEdit(self.groupBox)
        self.verifiContrasenaTelRespTxt.setGeometry(QtCore.QRect(400, 280, 141, 20))
        self.verifiContrasenaTelRespTxt.setObjectName(_fromUtf8("verifiContrasenaTelRespTxt"))
        self.emailRespTxt = QtGui.QLineEdit(self.groupBox)
        self.emailRespTxt.setGeometry(QtCore.QRect(400, 310, 141, 20))
        self.emailRespTxt.setObjectName(_fromUtf8("emailRespTxt"))
        self.fechaInicioDate = QtGui.QDateEdit(self.groupBox)
        self.fechaInicioDate.setGeometry(QtCore.QRect(120, 310, 141, 21))
        self.fechaInicioDate.setObjectName(_fromUtf8("fechaInicioDate"))
        self.fechaFinDate = QtGui.QDateEdit(self.groupBox)
        self.fechaFinDate.setGeometry(QtCore.QRect(120, 340, 141, 21))
        self.fechaFinDate.setObjectName(_fromUtf8("fechaFinDate"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.aceptarBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.agregarPersona)
        QtCore.QObject.connect(self.cancelarBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.cancelar)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.aceptarBtn.setText(_translate("Form", "Aceptar", None))
        self.cancelarBtn.setText(_translate("Form", "Cancelar", None))
        self.groupBox.setTitle(_translate("Form", "Datos Persona", None))
        self.amLbl.setText(_translate("Form", "Apellid Paterno:", None))
        self.gradoEscolarLbl.setText(_translate("Form", "Grado Escolar:", None))
        self.nombreLbl.setText(_translate("Form", "Nombre:", None))
        self.generoLbl.setText(_translate("Form", "Genero:", None))
        self.celularLbl.setText(_translate("Form", "Celular:", None))
        self.emailLbl.setText(_translate("Form", "E-Mail:", None))
        self.fechaNacDate.setDisplayFormat(_translate("Form", "yyyy/MM/dd", None))
        self.telefonoLbl.setText(_translate("Form", "Telefono:", None))
        self.domicilioLbl.setText(_translate("Form", "Domicilio:", None))
        self.coloniaLbl.setText(_translate("Form", "Colonia:", None))
        self.codigoPostalLbl.setText(_translate("Form", "Codigo Postal:", None))
        self.monitoreoAreaLbl.setText(_translate("Form", "Monitoreo:", None))
        self.fechaNacLbl.setText(_translate("Form", "Fecha Nacimiento:", None))
        self.apLbl.setText(_translate("Form", "Apellido Materno:", None))
        self.escuelaPuestoLbl.setText(_translate("Form", "temp:", None))
        self.permisosLbl.setText(_translate("Form", "Permisos:", None))
        self.usuarioTelEmeLbl.setText(_translate("Form", "temp", None))
        self.contrasenaNombreResLbl.setText(_translate("Form", "temp", None))
        self.verifiContrasenaTelRespLbl.setText(_translate("Form", "Tel. Responsable:", None))
        self.fechaInicioLbl.setText(_translate("Form", "Fecha inicio:", None))
        self.emailRespLbl.setText(_translate("Form", "E-Mail Responsable:", None))
        self.fechaFinLbl.setText(_translate("Form", "Fecha fin:", None))
        self.fechaInicioDate.setDisplayFormat(_translate("Form", "yyyy/MM/dd", None))
        self.fechaFinDate.setDisplayFormat(_translate("Form", "yyyy/MM/dd", None))

