# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cursos.ui'
#
# Created: Wed Feb 26 21:14:56 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(991, 740)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.dockWidget = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget.setEnabled(True)
        self.dockWidget.setGeometry(QtCore.QRect(20, 20, 941, 671))
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.busquedaLbl = QtGui.QLabel(self.dockWidgetContents)
        self.busquedaLbl.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.busquedaLbl.setObjectName(_fromUtf8("busquedaLbl"))
        self.tipoFiltroComboBox = QtGui.QComboBox(self.dockWidgetContents)
        self.tipoFiltroComboBox.setGeometry(QtCore.QRect(70, 40, 111, 22))
        self.tipoFiltroComboBox.setObjectName(_fromUtf8("tipoFiltroComboBox"))
        self.busquedaTxt = QtGui.QLineEdit(self.dockWidgetContents)
        self.busquedaTxt.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.busquedaTxt.setObjectName(_fromUtf8("busquedaTxt"))
        self.filtroLbl = QtGui.QLabel(self.dockWidgetContents)
        self.filtroLbl.setGeometry(QtCore.QRect(10, 40, 46, 13))
        self.filtroLbl.setObjectName(_fromUtf8("filtroLbl"))
        self.actualizarBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.actualizarBtn.setGeometry(QtCore.QRect(840, 40, 91, 23))
        self.actualizarBtn.setObjectName(_fromUtf8("actualizarBtn"))
        self.infoTableWidget = QtGui.QTableView(self.dockWidgetContents)
        self.infoTableWidget.setGeometry(QtCore.QRect(10, 70, 931, 571))
        self.infoTableWidget.setObjectName(_fromUtf8("infoTableWidget"))
        self.copiarBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.copiarBtn.setGeometry(QtCore.QRect(734, 40, 81, 23))
        self.copiarBtn.setObjectName(_fromUtf8("copiarBtn"))
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCursos = QtGui.QMenu(self.menubar)
        self.menuCursos.setObjectName(_fromUtf8("menuCursos"))
        self.menuVer = QtGui.QMenu(self.menuCursos)
        self.menuVer.setObjectName(_fromUtf8("menuVer"))
        self.menuEstudiante = QtGui.QMenu(self.menuVer)
        self.menuEstudiante.setObjectName(_fromUtf8("menuEstudiante"))
        self.menuVerPracticante = QtGui.QMenu(self.menuEstudiante)
        self.menuVerPracticante.setObjectName(_fromUtf8("menuVerPracticante"))
        self.menuVerPrestador = QtGui.QMenu(self.menuEstudiante)
        self.menuVerPrestador.setObjectName(_fromUtf8("menuVerPrestador"))
        self.menuVoluntarios = QtGui.QMenu(self.menuVer)
        self.menuVoluntarios.setObjectName(_fromUtf8("menuVoluntarios"))
        self.menuLista_Asistencia = QtGui.QMenu(self.menuVer)
        self.menuLista_Asistencia.setObjectName(_fromUtf8("menuLista_Asistencia"))
        self.menuAgregar = QtGui.QMenu(self.menuCursos)
        self.menuAgregar.setObjectName(_fromUtf8("menuAgregar"))
        self.menuAgregarEstudiante = QtGui.QMenu(self.menuAgregar)
        self.menuAgregarEstudiante.setObjectName(_fromUtf8("menuAgregarEstudiante"))
        self.menuPracticante = QtGui.QMenu(self.menuAgregarEstudiante)
        self.menuPracticante.setObjectName(_fromUtf8("menuPracticante"))
        self.menuPrestador_de_Servicio = QtGui.QMenu(self.menuAgregarEstudiante)
        self.menuPrestador_de_Servicio.setObjectName(_fromUtf8("menuPrestador_de_Servicio"))
        self.menuVoluntario = QtGui.QMenu(self.menuAgregar)
        self.menuVoluntario.setObjectName(_fromUtf8("menuVoluntario"))
        self.menuAlumnos = QtGui.QMenu(self.menubar)
        self.menuAlumnos.setObjectName(_fromUtf8("menuAlumnos"))
        self.menuAgregarAlumno = QtGui.QMenu(self.menuAlumnos)
        self.menuAgregarAlumno.setObjectName(_fromUtf8("menuAgregarAlumno"))
        self.menuVerAlumno = QtGui.QMenu(self.menuAlumnos)
        self.menuVerAlumno.setObjectName(_fromUtf8("menuVerAlumno"))
        self.menuReportes = QtGui.QMenu(self.menubar)
        self.menuReportes.setObjectName(_fromUtf8("menuReportes"))
        self.menuGenerar = QtGui.QMenu(self.menuReportes)
        self.menuGenerar.setObjectName(_fromUtf8("menuGenerar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionVerLista_cursos = QtGui.QAction(MainWindow)
        self.actionVerLista_cursos.setObjectName(_fromUtf8("actionVerLista_cursos"))
        self.actionVerAlumnos = QtGui.QAction(MainWindow)
        self.actionVerAlumnos.setObjectName(_fromUtf8("actionVerAlumnos"))
        self.actionAlumno = QtGui.QAction(MainWindow)
        self.actionAlumno.setObjectName(_fromUtf8("actionAlumno"))
        self.actionCurso = QtGui.QAction(MainWindow)
        self.actionCurso.setObjectName(_fromUtf8("actionCurso"))
        self.actionTemporada = QtGui.QAction(MainWindow)
        self.actionTemporada.setObjectName(_fromUtf8("actionTemporada"))
        self.actionAgregaCurso = QtGui.QAction(MainWindow)
        self.actionAgregaCurso.setObjectName(_fromUtf8("actionAgregaCurso"))
        self.actionAgregarMaestro = QtGui.QAction(MainWindow)
        self.actionAgregarMaestro.setObjectName(_fromUtf8("actionAgregarMaestro"))
        self.actionVerEstudiantes = QtGui.QAction(MainWindow)
        self.actionVerEstudiantes.setObjectName(_fromUtf8("actionVerEstudiantes"))
        self.actionAyudante_2 = QtGui.QAction(MainWindow)
        self.actionAyudante_2.setObjectName(_fromUtf8("actionAyudante_2"))
        self.actionCausa_falta = QtGui.QAction(MainWindow)
        self.actionCausa_falta.setObjectName(_fromUtf8("actionCausa_falta"))
        self.actionNuevo = QtGui.QAction(MainWindow)
        self.actionNuevo.setObjectName(_fromUtf8("actionNuevo"))
        self.actionNuevoAlumnoCurso = QtGui.QAction(MainWindow)
        self.actionNuevoAlumnoCurso.setObjectName(_fromUtf8("actionNuevoAlumnoCurso"))
        self.actionExistenteAlumnoCurso = QtGui.QAction(MainWindow)
        self.actionExistenteAlumnoCurso.setObjectName(_fromUtf8("actionExistenteAlumnoCurso"))
        self.actionExcel = QtGui.QAction(MainWindow)
        self.actionExcel.setObjectName(_fromUtf8("actionExcel"))
        self.actionPDF = QtGui.QAction(MainWindow)
        self.actionPDF.setObjectName(_fromUtf8("actionPDF"))
        self.actionVerTodosAlumnos = QtGui.QAction(MainWindow)
        self.actionVerTodosAlumnos.setObjectName(_fromUtf8("actionVerTodosAlumnos"))
        self.actionVerAlumnoCurso = QtGui.QAction(MainWindow)
        self.actionVerAlumnoCurso.setObjectName(_fromUtf8("actionVerAlumnoCurso"))
        self.actionVerTodosVoluntarios = QtGui.QAction(MainWindow)
        self.actionVerTodosVoluntarios.setObjectName(_fromUtf8("actionVerTodosVoluntarios"))
        self.actionVerVoluntariosCurso = QtGui.QAction(MainWindow)
        self.actionVerVoluntariosCurso.setObjectName(_fromUtf8("actionVerVoluntariosCurso"))
        self.actionPor_curso = QtGui.QAction(MainWindow)
        self.actionPor_curso.setObjectName(_fromUtf8("actionPor_curso"))
        self.actionNuevoVoluntarioCurso = QtGui.QAction(MainWindow)
        self.actionNuevoVoluntarioCurso.setObjectName(_fromUtf8("actionNuevoVoluntarioCurso"))
        self.actionExistenteVoluntarioCurso = QtGui.QAction(MainWindow)
        self.actionExistenteVoluntarioCurso.setObjectName(_fromUtf8("actionExistenteVoluntarioCurso"))
        self.actionPracticanteNuevo = QtGui.QAction(MainWindow)
        self.actionPracticanteNuevo.setObjectName(_fromUtf8("actionPracticanteNuevo"))
        self.actionPracticanteExistente = QtGui.QAction(MainWindow)
        self.actionPracticanteExistente.setObjectName(_fromUtf8("actionPracticanteExistente"))
        self.actionPrestadorNuevo = QtGui.QAction(MainWindow)
        self.actionPrestadorNuevo.setObjectName(_fromUtf8("actionPrestadorNuevo"))
        self.actionPrestadorExistente = QtGui.QAction(MainWindow)
        self.actionPrestadorExistente.setObjectName(_fromUtf8("actionPrestadorExistente"))
        self.actionTodosPracticante = QtGui.QAction(MainWindow)
        self.actionTodosPracticante.setObjectName(_fromUtf8("actionTodosPracticante"))
        self.actionCursoPracticante = QtGui.QAction(MainWindow)
        self.actionCursoPracticante.setObjectName(_fromUtf8("actionCursoPracticante"))
        self.actionTodosPrestador = QtGui.QAction(MainWindow)
        self.actionTodosPrestador.setObjectName(_fromUtf8("actionTodosPrestador"))
        self.actionCursoPrestador = QtGui.QAction(MainWindow)
        self.actionCursoPrestador.setObjectName(_fromUtf8("actionCursoPrestador"))
        self.actionAsistenciaPracticante = QtGui.QAction(MainWindow)
        self.actionAsistenciaPracticante.setObjectName(_fromUtf8("actionAsistenciaPracticante"))
        self.actionAsistenciaPrestador = QtGui.QAction(MainWindow)
        self.actionAsistenciaPrestador.setObjectName(_fromUtf8("actionAsistenciaPrestador"))
        self.actionAsistenciaAlumnos = QtGui.QAction(MainWindow)
        self.actionAsistenciaAlumnos.setObjectName(_fromUtf8("actionAsistenciaAlumnos"))
        self.menuVerPracticante.addAction(self.actionTodosPracticante)
        self.menuVerPracticante.addAction(self.actionCursoPracticante)
        self.menuVerPrestador.addAction(self.actionTodosPrestador)
        self.menuVerPrestador.addAction(self.actionCursoPrestador)
        self.menuEstudiante.addAction(self.menuVerPracticante.menuAction())
        self.menuEstudiante.addAction(self.menuVerPrestador.menuAction())
        self.menuVoluntarios.addAction(self.actionVerTodosVoluntarios)
        self.menuVoluntarios.addAction(self.actionVerVoluntariosCurso)
        self.menuLista_Asistencia.addAction(self.actionAsistenciaPracticante)
        self.menuLista_Asistencia.addAction(self.actionAsistenciaPrestador)
        self.menuLista_Asistencia.addAction(self.actionAsistenciaAlumnos)
        self.menuVer.addAction(self.actionVerLista_cursos)
        self.menuVer.addAction(self.menuEstudiante.menuAction())
        self.menuVer.addAction(self.menuVoluntarios.menuAction())
        self.menuVer.addAction(self.menuLista_Asistencia.menuAction())
        self.menuPracticante.addAction(self.actionPracticanteNuevo)
        self.menuPracticante.addAction(self.actionPracticanteExistente)
        self.menuPrestador_de_Servicio.addAction(self.actionPrestadorNuevo)
        self.menuPrestador_de_Servicio.addAction(self.actionPrestadorExistente)
        self.menuAgregarEstudiante.addAction(self.menuPracticante.menuAction())
        self.menuAgregarEstudiante.addAction(self.menuPrestador_de_Servicio.menuAction())
        self.menuVoluntario.addAction(self.actionNuevoVoluntarioCurso)
        self.menuVoluntario.addAction(self.actionExistenteVoluntarioCurso)
        self.menuAgregar.addAction(self.actionAgregaCurso)
        self.menuAgregar.addAction(self.menuAgregarEstudiante.menuAction())
        self.menuAgregar.addAction(self.actionCausa_falta)
        self.menuAgregar.addAction(self.menuVoluntario.menuAction())
        self.menuCursos.addAction(self.menuAgregar.menuAction())
        self.menuCursos.addAction(self.menuVer.menuAction())
        self.menuAgregarAlumno.addAction(self.actionNuevoAlumnoCurso)
        self.menuAgregarAlumno.addAction(self.actionExistenteAlumnoCurso)
        self.menuVerAlumno.addAction(self.actionVerTodosAlumnos)
        self.menuVerAlumno.addAction(self.actionVerAlumnoCurso)
        self.menuAlumnos.addAction(self.menuAgregarAlumno.menuAction())
        self.menuAlumnos.addAction(self.menuVerAlumno.menuAction())
        self.menuGenerar.addAction(self.actionExcel)
        self.menuReportes.addAction(self.menuGenerar.menuAction())
        self.menubar.addAction(self.menuCursos.menuAction())
        self.menubar.addAction(self.menuAlumnos.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionAgregaCurso, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarCurso)
        QtCore.QObject.connect(self.actionCausa_falta, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarCausaFaltaCurso)
        QtCore.QObject.connect(self.actionVerLista_cursos, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verCatalogoCursos)
        QtCore.QObject.connect(self.actionNuevoAlumnoCurso, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarAlumno)
        QtCore.QObject.connect(self.actionExistenteAlumnoCurso, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarAlumnoCurso)
        QtCore.QObject.connect(self.actionVerTodosAlumnos, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verAlumnos)
        QtCore.QObject.connect(self.actionVerTodosVoluntarios, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verVoluntario)
        QtCore.QObject.connect(self.actionVerVoluntariosCurso, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verVoluntarioCurso)
        QtCore.QObject.connect(self.actionVerAlumnoCurso, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verAlumnoCurso)
        QtCore.QObject.connect(self.actionNuevoVoluntarioCurso, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarVoluntario)
        QtCore.QObject.connect(self.actionExistenteVoluntarioCurso, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarVoluntarioCurso)
        QtCore.QObject.connect(self.actualizarBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actualizar)
        QtCore.QObject.connect(self.actionPracticanteNuevo, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarPracticante)
        QtCore.QObject.connect(self.actionPracticanteExistente, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarPracticanteCurso)
        QtCore.QObject.connect(self.actionPrestadorNuevo, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarPrestador)
        QtCore.QObject.connect(self.actionPrestadorExistente, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.agregarPrestadorCurso)
        QtCore.QObject.connect(self.actionTodosPracticante, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verPracticante)
        QtCore.QObject.connect(self.actionCursoPracticante, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verPracticanteCurso)
        QtCore.QObject.connect(self.actionTodosPrestador, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verPrestador)
        QtCore.QObject.connect(self.actionCursoPrestador, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verPrestadorCurso)
        QtCore.QObject.connect(self.actionAsistenciaAlumnos, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verAsistenciaAlumno)
        QtCore.QObject.connect(self.actionAsistenciaPracticante, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verAsistenciaPracticante)
        QtCore.QObject.connect(self.actionAsistenciaPrestador, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.verAsistenciaPrestador)
        QtCore.QObject.connect(self.tipoFiltroComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.actualizarFiltro)
        QtCore.QObject.connect(self.busquedaTxt, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.actualizarFiltro)
        QtCore.QObject.connect(self.infoTableWidget, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), MainWindow.agregarFilaAActualizar)
        QtCore.QObject.connect(self.copiarBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.copiar)
        QtCore.QObject.connect(self.actionExcel, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.enviarExcell)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema Informacion Crece", None))
        self.busquedaLbl.setText(_translate("MainWindow", "Busqueda:", None))
        self.filtroLbl.setText(_translate("MainWindow", "Filtro:", None))
        self.actualizarBtn.setText(_translate("MainWindow", "Actualizar", None))
        self.copiarBtn.setText(_translate("MainWindow", "Copiar", None))
        self.menuCursos.setTitle(_translate("MainWindow", "Programas", None))
        self.menuVer.setTitle(_translate("MainWindow", "Ver ", None))
        self.menuEstudiante.setTitle(_translate("MainWindow", "Estudiante", None))
        self.menuVerPracticante.setTitle(_translate("MainWindow", "Practicante", None))
        self.menuVerPrestador.setTitle(_translate("MainWindow", "Prestador de Servicio", None))
        self.menuVoluntarios.setTitle(_translate("MainWindow", "Voluntarios", None))
        self.menuLista_Asistencia.setTitle(_translate("MainWindow", "Lista Asistencia", None))
        self.menuAgregar.setTitle(_translate("MainWindow", "Agregar", None))
        self.menuAgregarEstudiante.setTitle(_translate("MainWindow", "Estudiante", None))
        self.menuPracticante.setTitle(_translate("MainWindow", "Practicante", None))
        self.menuPrestador_de_Servicio.setTitle(_translate("MainWindow", "Prestador de Servicio", None))
        self.menuVoluntario.setTitle(_translate("MainWindow", "Voluntario", None))
        self.menuAlumnos.setTitle(_translate("MainWindow", "Alumnos", None))
        self.menuAgregarAlumno.setTitle(_translate("MainWindow", "Agregar", None))
        self.menuVerAlumno.setTitle(_translate("MainWindow", "Ver", None))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes", None))
        self.menuGenerar.setTitle(_translate("MainWindow", "Generar", None))
        self.actionVerLista_cursos.setText(_translate("MainWindow", "Catalogo de cursos", None))
        self.actionVerAlumnos.setText(_translate("MainWindow", "Alumnos", None))
        self.actionAlumno.setText(_translate("MainWindow", "Alumno", None))
        self.actionCurso.setText(_translate("MainWindow", "Edad", None))
        self.actionTemporada.setText(_translate("MainWindow", "Maestro", None))
        self.actionAgregaCurso.setText(_translate("MainWindow", "Programa", None))
        self.actionAgregarMaestro.setText(_translate("MainWindow", "Maestro", None))
        self.actionVerEstudiantes.setText(_translate("MainWindow", "Maestros", None))
        self.actionAyudante_2.setText(_translate("MainWindow", "Estudiante", None))
        self.actionCausa_falta.setText(_translate("MainWindow", "Causa falta", None))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo", None))
        self.actionNuevoAlumnoCurso.setText(_translate("MainWindow", "Nuevo", None))
        self.actionExistenteAlumnoCurso.setText(_translate("MainWindow", "Existente", None))
        self.actionExcel.setText(_translate("MainWindow", "Excel", None))
        self.actionPDF.setText(_translate("MainWindow", "PDF", None))
        self.actionVerTodosAlumnos.setText(_translate("MainWindow", "Todos", None))
        self.actionVerAlumnoCurso.setText(_translate("MainWindow", "Por curso", None))
        self.actionVerTodosVoluntarios.setText(_translate("MainWindow", "Todos", None))
        self.actionVerVoluntariosCurso.setText(_translate("MainWindow", "Por curso", None))
        self.actionPor_curso.setText(_translate("MainWindow", "Por curso", None))
        self.actionNuevoVoluntarioCurso.setText(_translate("MainWindow", "Nuevo", None))
        self.actionExistenteVoluntarioCurso.setText(_translate("MainWindow", "Existente", None))
        self.actionPracticanteNuevo.setText(_translate("MainWindow", "Nuevo", None))
        self.actionPracticanteExistente.setText(_translate("MainWindow", "Existente", None))
        self.actionPrestadorNuevo.setText(_translate("MainWindow", "Nuevo", None))
        self.actionPrestadorExistente.setText(_translate("MainWindow", "Existente", None))
        self.actionTodosPracticante.setText(_translate("MainWindow", "Todos", None))
        self.actionCursoPracticante.setText(_translate("MainWindow", "Por Curso", None))
        self.actionTodosPrestador.setText(_translate("MainWindow", "Todos", None))
        self.actionCursoPrestador.setText(_translate("MainWindow", "Por Curso", None))
        self.actionAsistenciaPracticante.setText(_translate("MainWindow", "Practicante", None))
        self.actionAsistenciaPrestador.setText(_translate("MainWindow", "Prestador", None))
        self.actionAsistenciaAlumnos.setText(_translate("MainWindow", "Alumnos", None))

